// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI8M3uN8s9QluTKX8KADC35q60kjLSBWg',
    appId: '1:1055394808593:web:a4d6ad4079a27741ae02b0',
    messagingSenderId: '1055394808593',
    projectId: 'quickbites-4e15d',
    authDomain: 'quickbites-4e15d.firebaseapp.com',
    storageBucket: 'quickbites-4e15d.appspot.com',
    measurementId: 'G-MRREB98GL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzBLLSBXb1mOixdQypaZkRYL2WOHslbq4',
    appId: '1:1055394808593:android:ba4ad42ea6e82832ae02b0',
    messagingSenderId: '1055394808593',
    projectId: 'quickbites-4e15d',
    storageBucket: 'quickbites-4e15d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUlCJEiKviip0law-yvCDQupn82kGoTa4',
    appId: '1:1055394808593:ios:0718f4c05cea7913ae02b0',
    messagingSenderId: '1055394808593',
    projectId: 'quickbites-4e15d',
    storageBucket: 'quickbites-4e15d.appspot.com',
    androidClientId: '1055394808593-de2lhm41onjk4hpgvdpsr407bdlq8u92.apps.googleusercontent.com',
    iosClientId: '1055394808593-borf94h70sra0gr8na8ft8udmridj4nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUlCJEiKviip0law-yvCDQupn82kGoTa4',
    appId: '1:1055394808593:ios:0718f4c05cea7913ae02b0',
    messagingSenderId: '1055394808593',
    projectId: 'quickbites-4e15d',
    storageBucket: 'quickbites-4e15d.appspot.com',
    androidClientId: '1055394808593-de2lhm41onjk4hpgvdpsr407bdlq8u92.apps.googleusercontent.com',
    iosClientId: '1055394808593-borf94h70sra0gr8na8ft8udmridj4nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.food',
  );
}
